const sortAndFiltersActions = {
    UPDATE_SEARCH_LANGUAGE: 'UPDATE_SEARCH_LANGUAGE',
    UPDATE_RELEASE_DATE: 'UPDATE_RELEASE_DATE',
    UPDATE_SELECT_SORT_VALUE: 'UPDATE_SELECT_SORT_VALUE',
    UPDATE_SEARCH_INPUT_VALUE: 'UPDATE_SEARCH_INPUT_VALUE',
}

export default sortAndFiltersActions;
