const usersActions = {
    SIGNUP: 'SIGNUP',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    UPDATE_REGISTER_USER_DATA: 'UPDATE_REGISTER_USER_DATA',
    GET_SESSION_ID: 'GET_SESSION_ID',
    GET_USER_ACCOUNT: 'GET_USER_ACCOUNT',
}

export default usersActions;