const moviesActions = {
    GET_MOVIES: 'GET_MOVIES',
    GET_FAVORITE_MOVIES: 'GET_FAVORITE_MOVIES',
    GET_MOVIE: 'GET_MOVIE',
    GET_GENRES: 'GET_GENRES',
    GET_LANGUAGES: 'GET_LANGUAGES',
    UPDATE_SEARCH_LANGUAGE: 'UPDATE_SEARCH_LANGUAGE',
    UPDATE_RELEASE_DATE: 'UPDATE_RELEASE_DATE',
    UPDATE_SELECT_SORT_VALUE: 'UPDATE_SELECT_SORT_VALUE',
    SORT_MOVIE_BY: 'SORT_MOVIE_BY',
    SEARCH_FILM: 'SEARCH_MOVIE',
    TOGGLE_LOADER: 'TOGGLE_LOADER',
    UPDATE_PAGINATION: 'UPDATE_PAGINATION',
    UPDATE_SEARCH_INPUT_VALUE: 'UPDATE_SEARCH_INPUT_VALUE',
    UPDATE_MOVIE_ACCOUNT_STATES: 'UPDATE_MOVIE_ACCOUNT_STATES',
    UPDATE_MOVIE_FAVORITE: 'UPDATE_MOVIE_FAVORITE'
}

export default moviesActions;