const moviesActions = {
    GET_MOVIES: 'GET_MOVIES',
    GET_FAVORITE_MOVIES: 'GET_FAVORITE_MOVIES',
    GET_MOVIE: 'GET_MOVIE',
    SEARCH_FILM: 'SEARCH_MOVIE',
    UPDATE_MOVIE_ACCOUNT_STATES: 'UPDATE_MOVIE_ACCOUNT_STATES',
    UPDATE_MOVIE_FAVORITE: 'UPDATE_MOVIE_FAVORITE',
    RESET_SELECTED_MOVIE: 'RESET_SELECTED_MOVIE',
    RESET_MOVIE_ACCOUNT_STATES: 'RESET_MOVIE_ACCOUNT_STATES'
}

export default moviesActions;
