const moviesActions = {
    GET_MOVIES: 'GET_MOVIES',
    GET_MOVIE: 'GET_MOVIE',
    SEARCH_FILM: 'SEARCH_MOVIE',
    TOGGLE_LOADER: 'TOGGLE_LOADER',
    UPDATE_PAGINATION: 'UPDATE_PAGINATION',
    UPDATE_SEARCH_INPUT_VALUE: 'UPDATE_SEARCH_INPUT_VALUE',
}

export default moviesActions;